name: Lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    if: contains(github.event.head_commit.message, '[ci skip]') == false
    runs-on: ubuntu-latest
    container: rocker/tidyverse
    steps:
      - uses: actions/checkout@v4
      - name: Install apt-get dependencies
        run: |
          apt-get update
          apt-get install git ssh curl bzip2 libffi-dev -y
      - name: Install lintr
        run: |
          Rscript -e "install.packages('lintr', repos = 'https://cloud.r-project.org')"
        shell:
          bash
      - name: Running lintr
        run: |
          Rscript -e "library(lintr); lint_package()"
        shell:
          bash
